### PR TITLE
Update dependency and minor cleanup

### PR DESCRIPTION
**Pull request by afwlehmann**

### CODE REVIEW

**Comment by tfausak** [comment]
:+1: These changes would be nice to have. `binary` would have to be bumped again; it's on 0.8 now.

**Comment by afwlehmann** [comment]
@tfausak Not sure about the current maintentance status of `bmp`.

**Comment by tfausak** [comment]
@benl23x5 is there anything we can do to help merge this PR?

**Comment by benl23x5** [comment]
Thanks, I ended up merging this by hand. BMP is plenty maintained, but I don't check github notifications every day. If a PR is posted in the forest but no one is around to see it..

**Pull request closed without merging**
